### ISSUE TITLE
Support for Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by jangeador** [schtritoff/hyperv-vm-provisioning#12]
Ubuntu 24.04 LTS is out, can we please add support for that version?

**Comment by samstagern** [comment]
I filed a pull request for that: https://github.com/schtritoff/hyperv-vm-provisioning/pull/14

**Comment by schtritoff** [comment]
merged https://github.com/schtritoff/hyperv-vm-provisioning/pull/13
