### ISSUE TITLE
Serial console - Named pipe

### ISSUE THREAD

**Issue by AvrumFeldman** [schtritoff/hyperv-vm-provisioning#4]
Hi,

During my quest to streamline our Linux machine setups I came across your amazing script and love it! 

Are you able to get the serial console output to a named pipe? I tried and it just doesn't work, and based on the documentation from Microsoft [here](https://learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps#example-1:~:text=You%20will%20have%20to%20write%20your%20own%20application%20to%20create%20a%20named%20pipe) it seems the named pipe must already exist in order for HyperV to be able to use it, which adds up as I checked use pipelist and I didn't see the named pipe used.

Regards,

**Comment by schtritoff** [comment]
Did you try with `ShowSerialConsoleWindow` [switch](https://github.com/schtritoff/hyperv-vm-provisioning/blob/2a8b38a2816e630fe363d08602dff6865b4dfd87/New-HyperVCloudImageVM.ps1#LL1177C6-L1177C29)? Try to see if there is a named pipe with the same name before creating VM, for example with[pipelist](https://learn.microsoft.com/en-us/sysinternals/downloads/pipelist).

**Comment by AvrumFeldman** [comment]
Confirmed there is no named pipe with the same name.

I honestly didn't use your script, I tried it manually on a VM I created manually. (PowerShell window was elevated).

**Comment by AvrumFeldman** [comment]
Nevermind, I now tested with a new VM and the pipe was created and putty was able to connect, albeit with no output showing up on terminal.

I don't know what I did different this time, my only guess is that it's possible the previous VM creation wasn't done using elevated console so adding afterwards the named pipe even from an elevated session doesn't work.

Will do some testing.

**Comment by AvrumFeldman** [comment]
Update: Seems that the ISO installer doesn't output to ttyS0 while the cloud images do. (This doesn't answer why it wasn't working yesterday, but it's working now so screw it 😀).
