### ISSUE TITLE
Automate Static IP

### ISSUE THREAD

**Issue by MickG72** [schtritoff/hyperv-vm-provisioning#6]
Script is working well 
What are the steps to have the VM use a static IP
New-HyperVCloudImageVM would need to be updated or i need to pass some variables to script
Can't work it out
Trying this an ubuntu vm
Thanks

**Comment by schtritoff** [comment]
There is an example in script header how to create VM with static IP https://github.com/schtritoff/hyperv-vm-provisioning/blob/5e74ed4c3c52219622f0bde1038a2854429feacd/New-HyperVCloudImageVM.ps1#L6 

Basically you need to pass some parameters to the script and it should work
`
 -NetAddress 192.168.188.12 -NetNetmask 255.255.255.0 -NetGateway 192.168.188.1 -NameServers "192.168.188.1"
`

**Comment by MickG72** [comment]
I missed it ,  thanks for the follow up 
All working great
Thanks

**Comment by MickG72** [comment]
Hi 
This process works for Debian builds
With Ubuntu build , I get this error 
“Warning : no network configuration version type defined for static is address setup”

**Comment by tiborauer** [comment]
Can you use it also to specify IP6 addresses?
