### ISSUE TITLE
Automate Static IP (Ubuntu)

### ISSUE THREAD

**Issue by MickG72** [schtritoff/hyperv-vm-provisioning#7]
Static IP for Debian build is working fine.
If I select image version as 22.04, it comes up with an error, but continues to build the  vm with a dhcp setting.
Error : "WARNING: No Network Configuration version type defined for static IP address setup"
If I add a variable :  "$NetConfigType=v1" , I get no errors, but the static IP is not applied. Neither is the username/password

Command I am using is : 
./New-HyperVCloudImageVM.ps1 -VMProcessorCount 2 -VMMemoryStartupBytes 2GB -VHDSizeBytes 8GB -VMName Ubuntu -ImageVersion "22.04" -virtualSwitchName "Home" -VMGeneration 2 -GuestAdminUsername admin -GuestAdminPassword password -VMMachine_StoragePath "D:\VM\" -NetAddress 192.168.10.10 -NetNetmask 255.255.255.0 -NetGateway 192.168.10.1 -NameServers 8.8.8.8 -NetConfigType "v1"

 Which setting for this variable should it be for Ubuntu builds ? I can't get either to work
Does it require more info ?

**Comment by schtritoff** [comment]
for reference - this one is working in my case https://github.com/schtritoff/hyperv-vm-provisioning/blob/80a1b650f926c7ae6999422b903ed21214be01cf/New-HyperVCloudImageVM.ps1#L6
